=== StanNitrogen/DataAnalysisWeb/web/classes/WEB-INF/classes/WEB-INF/classes/WEB-INF/classes/com/songtech/ypoi/xml/excel.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3school.com.cn"
           xmlns="http://www.w3school.com.cn"
           elementFormDefault="qualified">


    <xs:element name="Excel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sheets">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="Sheet" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Sheet">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Titles" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" maxOccurs="1">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="titleName" type="xs:string"/>
                                        <xs:element name="titleStartRow" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="titleRowspan" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="titleStartColumn" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="titleColspan" type="xs:integer" minOccurs="0"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Columns">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="column" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="fieldName" type="xs:string" nillable="false"/>
                                        <xs:element name="colName" type="xs:string" nillable="false"/>
                                        <xs:element name="orderNum" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="width" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="type" type="xs:integer" minOccurs="0"/>
                                        <xs:element name="importFormatter" type="xs:string" minOccurs="0"/>
                                        <xs:element name="exportFormatter" type="xs:string" minOccurs="0"/>
                                        <xs:element name="isImport" type="xs:boolean" minOccurs="0"/>
                                    </xs:all>
                                </xs:complexType>
                                <xs:unique name="columnUnique">
                                    <xs:selector xpath=".//column"/>
                                    <xs:field xpath="VOName"/>
                                </xs:unique>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="sheetName" type="xs:string"/>
            <xs:attribute name="sheetOrder" type="xs:integer" use="required"/>
            <xs:attribute name="classPath" type="xs:string"/>
        </xs:complexType>
        <xs:unique name="SheetUnique">
            <xs:selector xpath=".//Sheet"/>
            <xs:field xpath="@sheetOrder"/>
        </xs:unique>
    </xs:element>

</xs:schema>

=== StanNitrogen/DataAnalysisWeb/web/classes/com/songtech/ypoi/xml/excel-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<Excel xmlns="http://www.w3school.com.cn"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.w3school.com.cn excel.xsd">
    <Sheets>
        <Sheet sheetName="all" sheetOrder="0">
            <Titles>
                <title>
                    <titleName>qqqq</titleName>
                    <titleStartRow>2</titleStartRow>
                    <titleRowspan>2</titleRowspan>
                    <titleStartColumn>0</titleStartColumn>
                    <titleColspan>1</titleColspan>
                </title>
            </Titles>
            <Columns>
                <column>
                    <colName>共享</colName>
                    <fieldName>share</fieldName>
                </column>
                <column>
                    <colName>共享率</colName>
                    <fieldName>shareRate</fieldName>
                    <orderNum>0</orderNum>
                    <exportFormatter>YYYY-MM-DD</exportFormatter>
                    <importFormatter>YYYY-MM-DD</importFormatter>
                    <isImport>true</isImport>
                    <type>1</type>
                    <width>4</width>
                </column>
                <column>
                    <colName>率</colName>
                    <fieldName>Rate</fieldName>
                    <orderNum>9</orderNum>
                </column>
                <column>
                    <colName>共享率4</colName>
                    <fieldName>shareRate1</fieldName>
                    <orderNum>4</orderNum>
                    <exportFormatter>YYYY-MM-DD</exportFormatter>
                    <importFormatter>YYYY-MM-DD</importFormatter>
                    <isImport>true</isImport>
                    <type>1</type>
                    <width>4</width>
                </column>
            </Columns>
        </Sheet>
        <!--&lt;!&ndash;必填样例&ndash;&gt;-->
        <!--<Sheet sheetName="required" sheetOrder="1">-->
            <!--<Titles>-->
                <!--<title>-->
                    <!--<titleName></titleName>-->
                <!--</title>-->
            <!--</Titles>-->
            <!--<Columns>-->
                <!--<column>-->
                    <!--<excelName></excelName>-->
                    <!--<colName></colName>-->
                <!--</column>-->
                <!--<column>-->
                    <!--<excelName></excelName>-->
                    <!--<colName></colName>-->
                <!--</column>-->
            <!--</Columns>-->
        <!--</Sheet>-->
    </Sheets>
</Excel>

=== StanNitrogen/DataAnalysisWeb/web/classes/WEB-INF/classes/com/songtech/ypoi/xml/ex-util-test.xml
<?xml version="1.0" encoding="UTF-8"?>
<Excel xmlns="http://www.w3school.com.cn"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.w3school.com.cn excel.xsd">
    <Sheets>
        <Sheet sheetName="殷楠测试1" sheetOrder="0" classPath="com.songtech.ypoi.test.testModel.TestModel">
            <Titles>
                <title>
                    <titleName>标题</titleName>
                </title>
            </Titles>
            <Columns>
                <column>
                    <colName>test1</colName>
                    <fieldName>test1</fieldName>
                    <isImport>true</isImport>
                </column>
                <column>
                    <colName>test2</colName>
                    <fieldName>test2</fieldName>
                    <isImport>true</isImport>
                </column>
                <column>
                    <colName>test3</colName>
                    <fieldName>test3</fieldName>
                    <exportFormatter>YYYY-MM-DD</exportFormatter>
                    <isImport>true</isImport>
                </column>
                <column>
                    <colName>gogogo</colName>
                    <fieldName>gogogo</fieldName>
                    <orderNum>4</orderNum>
                    <isImport>true</isImport>
                    <type>1</type>
                    <width>4</width>
                </column>
            </Columns>
        </Sheet>
        <Sheet sheetName="殷楠测试2" sheetOrder="1" classPath="com.songtech.ypoi.test.testModel.TestModel2">
            <Columns>
                <column>
                    <colName>双精度</colName>
                    <fieldName>aDouble</fieldName>
                    <isImport>true</isImport>
                </column>
                <column>
                    <colName>高精度</colName>
                    <fieldName>bigDecimal</fieldName>
                    <isImport>true</isImport>
                </column>
                <column>
                    <colName>测试测试ccc</colName>
                    <fieldName>ceshi</fieldName>
                    <isImport>true</isImport>
                </column>
                <column>
                    <colName>时间</colName>
                    <fieldName>dateqqq</fieldName>
                    <exportFormatter>YYYY-MM-DD</exportFormatter>
                    <type>1</type>
                    <width>4</width>
                </column>
                <column>
                    <colName>随意字符串</colName>
                    <fieldName>ccc</fieldName>
                    <orderNum>4</orderNum>
                    <type>1</type>
                    <width>4</width>
                </column>
            </Columns>
        </Sheet>
        <!--&lt;!&ndash;必填样例&ndash;&gt;-->
        <!--<Sheet sheetName="required" sheetOrder="1">-->
            <!--<Titles>-->
                <!--<title>-->
                    <!--<titleName></titleName>-->
                <!--</title>-->
            <!--</Titles>-->
            <!--<Columns>-->
                <!--<column>-->
                    <!--<excelName></excelName>-->
                    <!--<colName></colName>-->
                <!--</column>-->
                <!--<column>-->
                    <!--<excelName></excelName>-->
                    <!--<colName></colName>-->
                <!--</column>-->
            <!--</Columns>-->
        <!--</Sheet>-->
    </Sheets>
</Excel>
